#!/usr/bin/env bash
# Stop hook — session-end reflection for kit self-improvement.
# Fires when Claude finishes responding. Checks for kit-file edits this session
# and writes an improvement proposal to docs/kit/improvements/pending/.
#
# SCOPE: craft-kit development only. This hook is NOT intended for project
# teams using craft-kit as a template. If you copied this repo for a project,
# remove this hook from .claude/settings.json (Stop section).
#
# Idempotent: one file per date. Re-runs on the same day are no-ops.
# Consumed by: kit-improve (kit improve).

set -euo pipefail
cd "$(git rev-parse --show-toplevel 2>/dev/null)" 2>/dev/null || exit 0

# Scope guard: only run inside the craft-kit repo itself.
# Project copies should remove docs/kit/improvements/ to disable this hook.
[ -d "docs/kit/improvements" ] || exit 0

# Read session_id from Stop hook stdin
input=$(cat 2>/dev/null || echo "{}")
session_id=$(echo "$input" | python3 -c "
import sys, json
print(json.load(sys.stdin).get('session_id', ''))
" 2>/dev/null || echo "")

[ -z "$session_id" ] && exit 0

# Filter current session's tracked files (format: "session_id|file_path")
TRACKED="/tmp/cc-files-all.txt"
[ -f "$TRACKED" ] || exit 0

session_files=$(grep "^${session_id}|" "$TRACKED" 2>/dev/null | cut -d'|' -f2 | sort -u || echo "")
[ -z "$session_files" ] && exit 0

# Only proceed if kit-relevant files were modified
# Kit files live in: scripts/, docs/, .claude/, and root config files
kit_files=$(echo "$session_files" | grep -E '(scripts/|docs/|\.claude/|CLAUDE\.md|HARNESS\.md|README\.md)' || true)
[ -z "$kit_files" ] && exit 0

date_str=$(date +%Y-%m-%d)
out_dir="docs/kit/improvements/pending"
out_file="${out_dir}/${date_str}.md"

# One reflection file per day — don't overwrite if already generated
[ -f "$out_file" ] && exit 0

mkdir -p "$out_dir"

{
  echo "# Session Reflection — ${date_str}"
  echo ""
  echo "## Kit files modified this session"
  echo "$kit_files" | sed 's/^/- /'
  echo ""
  echo "## Patterns to review (checklist)"
  echo ""
  echo "- [ ] Any hook gap — something Claude did that a hook should have caught?"
  echo "- [ ] Any procedure step that was unclear or required re-reading?"
  echo "- [ ] Any CLAUDE.md rule that was silently ignored or misapplied?"
  echo "- [ ] Any new pattern in kit workflows that deserves a procedure or rule?"
  echo "- [ ] Does HARNESS.md accurately reflect the change made?"
  echo ""
  echo "## Proposed kit improvements"
  echo ""
  echo "_Fill specific proposals based on the checklist above, then trigger kit-improve._"
  echo ""
  echo "---"
  echo "*Auto-generated by \`scripts/hooks/session-reflect.sh\`. Process with kit-improve.*"
} > "$out_file"

echo "[session-reflect] Improvement proposal saved: ${out_file}" >&2
